### ISSUE TITLE
Update to cats-effect 3

### ISSUE THREAD

**Issue by Daenyth** [higherkindness/mu-scala#1238]
Note that Monix isn't out for CE3 yet, so this will probably want to be an RC release first, without monix

**Comment by Dr-Nikson** [comment]
Any progress on this?)

**Comment by fedefernandez** [comment]
This has been addressed in version [v0.27.0](https://github.com/higherkindness/mu-scala/releases/tag/v0.27.0). Thanks to all participants, specially @Daenyth
