### ISSUE TITLE
Optional fields in proto2 files

### ISSUE THREAD

**Issue by randm-ch** [higherkindness/mu-scala#1300]
A proto definition

```
message UnlockEvent {
    optional string eventId = 1;
}
```

compiles to

```
final case class UnlockEvent(@_root_.pbdirect.pbIndex(1) eventId: _root_.java.lang.String)
```

whereas I would expect it to be

```
final case class UnlockEvent(@_root_.pbdirect.pbIndex(1) eventId: _root_.scala.Option[_root_.java.lang.String])
```

Is there an option for this (haven't found anything in the docs)? It works correctly if using another message BTW:

```
message EventId {
    string value = 1;
}

message UnlockEvent {
    optional EventId eventId = 1;
}
```

will result in `Option[EventId]` correctly.

Using `addSbtPlugin("io.higherkindness" % "sbt-mu-srcgen" % "0.26.0")`. Thanks!

**Comment by fedefernandez** [comment]
hi @randm-ch,

`sbt-mu-srcgen` uses skeumorph by default for the source generation. There's an issue related to this:

* https://github.com/higherkindness/skeuomorph/issues/218

You can use *avrohugger* for the code generation through the SBT setting key `muSrcGenAvroGeneratorType`. Take a look to [the documentation](https://higherkindness.io/mu-scala/reference/source-generation).

**Comment by randm-ch** [comment]
Thanks for the explaination and the workaround. Closing the issue.
