### ISSUE TITLE
Adding Server Reflection/Usage with gRPCurl 

### ISSUE THREAD

**Issue by chaddaksha** [higherkindness/mu-scala#1506]
Hi,

I've started building a gRPC service, for which I want to use gRPCurl for preliminary testing. Is it possible to do so with server reflection?

I've tried pulling in the `io.grpc.grpc-services` dependency and manually injecting the reflection service as so:
```scala
  server <- GrpcServer.default[IO](
    12345,
    List(AddService(myService), AddBindableService(ProtoReflectionService.newInstance()))
   )
```

Still, when trying to list the services, the only service that comes up is the `ServerReflection` service:
```bash
$ grpcurl -plaintext localhost:12345 list
grpc.reflection.v1alpha.ServerReflection
$ grpcurl -plaintext localhost:12345 describe
grpc.reflection.v1alpha.ServerReflection is a service:
service ServerReflection {
  rpc ServerReflectionInfo ( stream .grpc.reflection.v1alpha.ServerReflectionRequest ) returns ( stream .grpc.reflection.v1alpha.ServerReflectionResponse );
}
```

This same behavior occurs when using the giter8 template and injecting a `ProtoReflectionService` instance.

I would appreciate any thoughts/help.

Thanks,
Chad Daksha

**Comment by chaddaksha** [comment]
Hi, just following up on this to see if anyone has any thoughts.

Thanks,
Chad

**Comment by chaddaksha** [comment]
Hello,

Wondering if anyone could help on this.

Thank you,
Chad

**Comment by fedefernandez** [comment]
@chaddaksha, thanks for the ticket submission. I've been looking, and sadly we don't have support for reflection at this moment. It seems to be an experimental API that is not currently supported by the mechanisms we use to build the server.

![Screenshot 2022-10-11 at 13 09 32](https://user-images.githubusercontent.com/720923/195075263-1c6ab032-f337-4e9b-bf3e-0d348c9a511c.png)

A more detailed description is below

The reflection service is looking for that `schemaDescriptor` of type `ProtoFileDescriptorSupplier`

https://github.com/grpc/grpc-java/blob/d4fa0ecc07495097453b0a2848765f076b9e714c/services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java#L103

Currently, the only way to provide that value is through the service descriptor builder

https://github.com/grpc/grpc-java/blob/d4fa0ecc07495097453b0a2848765f076b9e714c/api/src/main/java/io/grpc/ServiceDescriptor.java#L191-L194

But we're using the `ServerServiceDefinition.Builder.addMethod` to create the server

https://github.com/higherkindness/mu-scala/blob/65efe5b63472eba7fd92fe1141c8c41252e54e18/modules/service/src/main/scala/higherkindness/mu/rpc/internal/service/GRPCServiceDefBuilder.scala#L32

That creates the `ServiceDescriptor` using the constructor, which doesn't include the ability to pass a `SchemaDescriptor`

https://github.com/grpc/grpc-java/blob/d4fa0ecc07495097453b0a2848765f076b9e714c/api/src/main/java/io/grpc/ServiceDescriptor.java#L63-L65

**Comment by fedefernandez** [comment]
The positive news is you can call the method by passing the `proto` file. I've been able to do it with the g8 template:

```
# hello.proto copied from src/main/resources/proto/hello.proto
./grpc_cli call localhost:12345 SayHello "name: 'Fede'" --protofiles=hello.proto --noremotedb
connecting to localhost:12345
greeting: "Hello, Fede!"
happy: true
Rpc succeeded with OK status
```

**Comment by chaddaksha** [comment]
Good to know, thank you for looking into this. We will proceed by continuing to pass the `proto` file when calling the method.
