### ISSUE TITLE
OpenAPI support

### ISSUE THREAD

**Issue by SemanticBeeng** [higherkindness/mu-scala#549]
Please provide support for `OpenAPI` as suggested in ["Introducing Mu: A purely functional library for building microservices"](https://www.47deg.com/blog/introducing-the-mu-open-source-library/).

> "Protocol support and code generation: Avro, Protocol Buffers, and Open API (coming soon)."

This suggests plans but nothing in code so far.
Please provide guidance, resources, etc if someone were to proceed with this given your thinking.

**Comment by SemanticBeeng** [comment]
Could we simply use https://github.com/NYTimes/openapi2proto ?
> _" accept an OpenAPI/Swagger definition (yaml or JSON) and generate a Protobuf v3 schema and gRPC service definition from it."_

**Comment by juanpedromoreno** [comment]
Thanks @SemanticBeeng , the support for `OpenApi` is already a work in progress. We'll be posting the roadmap for this feature soon.

A big part of `mu-http` feature is relying on https://github.com/higherkindness/skeuomorph .

**Comment by SemanticBeeng** [comment]
thanks Juan - looking forward to details.

I figured that for handling schema `skeumorph` is good but what about runtime support?

This seems useful https://www.beyondthelines.net/computing/grpc-rest-gateway-in-scala/.

If you can shed some light in this design regard and offer some ETA so I can plan ahead I would be grateful.

**Comment by juanpedromoreno** [comment]
This feature has been already released, please, feel free to reopen if you find any issues. Thanks!
