### ISSUE TITLE
Rename repository to mu-scala

### ISSUE THREAD

**Issue by raulraja** [higherkindness/mu-scala#582]
since we have `mu-kt` for the Kotlin counterpart

**Comment by calvellido** [comment]
A reminder that if we do this we could be having:

- Mu generic site: ~https://higherkindness.io/mu-services/~ https://higherkindness.io/mu/
- Mu Scala docs: ~https://higherkindness.io/mu/~ -> https://higherkindness.io/mu-scala/
- Mu Kotlin docs:
  - https://higherkindness.io/mu-kotlin/ (current placeholder) or
  - http://higherkindness.io/mu-kt/ (this one didn't really have any conflict actually)

**Comment by raulraja** [comment]
Yeah we need to share branding and integrate this project under the brand.
The docs should be the same for both showing examples in Kotlin and in
Scala . We plan on following the same design pattern but over suspended
functions and arrow fx. I think we should cross brand too the site so it's
mentioned in arrow and viceversa

**Comment by juanpedromoreno** [comment]
This is now done!
