### ISSUE TITLE
mu AST skeuomorph printers for http clients

### ISSUE THREAD

**Issue by fedefernandez** [higherkindness/mu-scala#592]
In order to provide OpenAPI client derivation, we need to develop a special printer that generates an algebra with the http4s clients (through code gen).

This need to have support for different library versions and combinations:

* http4s 0.18.x + circe 0.9.x
* http4s 0.20.x + circe 0.11.x

And ease the addition of new combinations.

**Comment by juanpedromoreno** [comment]
This was already implemented and released :)
