### ISSUE TITLE
Coproduct source geneation is broken

### ISSUE THREAD

**Issue by AdrianRaFo** [higherkindness/mu-scala#603]
If I have a scala protocol like this
```
  @message final case class PeopleResponse(result: Person :+: NotFoundError :+: DuplicatedPersonError :+: CNil) extends People
```
The generated `proto` (it fails for `avro` too) is
```
message PeopleResponse {
  $colon$plus$colon[Person, $colon$plus$colon[NotFoundError, $colon$plus$colon[DuplicatedPersonError, CNil]]] result = 1;
}
```

The generation ends well but the protocol generated is not usable

**Comment by fedefernandez** [comment]
Do we know from which version we have this problem?

**Comment by AdrianRaFo** [comment]
Not sure about from which version but it's on the 0.18.0

**Comment by fedefernandez** [comment]
Do you mind to check this (for `avro`) with older versions?

**Comment by AdrianRaFo** [comment]
It's failing from `0.14.0`, it was fine on `0.13.0`

**Comment by fedefernandez** [comment]
Thank you so much

**Comment by juanpedromoreno** [comment]
This is now outdated since the idl generation has been removed recently after its deprecation in previous versions.
