### ISSUE TITLE
website does not exist

### ISSUE THREAD

**Issue by francisdb** [higherkindness/mu-scala#730]
The repo header points to https://higherkindness.github.io/mu-services which returns 404

**Comment by cb372** [comment]
Oops, that's an old URL. The correct link would be either https://higherkindness.github.io/mu or https://higherkindness.github.io/mu-scala.

@juanpedromoreno Could you update it please? Looks like I don't have enough permissions to do so.

**Comment by juanpedromoreno** [comment]
Done! 

Thanks @francisdb for pointing it out
