### ISSUE TITLE
Cross compilation with scala 2.13

### ISSUE THREAD

**Issue by AdrianRaFo** [higherkindness/mu-scala#787]
Could we add cross-compilation with 2.13? AFAIK this is the only library we use without being published for 2.13 on the cats ecosystem and it's blocking some services to be upgraded. 
Is there any blocker to achieving this?

**Comment by cb372** [comment]
I had a look into this recently. I think the only blockers are:

* the avro4s upgrade (#770), which I started and then handed over to @naree. It looks like he hasn't had a chance to work on it yet.
* migrating the docs from tut to mdoc (#768), which was started by @juanpedromoreno

**Comment by juanpedromoreno** [comment]
Besides the WIPs and pending releases, I have another WIP doing cross-compilation. Will push once everything is in place 👍
