### ISSUE TITLE
Audit and re-organise the sbt project structure

### ISSUE THREAD

**Issue by cb372** [higherkindness/mu-scala#825]
IMO the current module structure is quite confusing and too granular. We have a lot of nanomodules with only one or two files, and a lot of inter-module dependencies. This makes the codebase difficult to navigate and the build really slow.

It's also not clear why certain classes are in certain modules. Files could be moved to more appropriate modules, or modules could be renamed to better reflect their contents.

A few examples of foibles I've found recently:

* The `mu-rpc-fs2` and `mu-rpc-monix` modules contain only a health-check service implementation. Is this example code, or library code that we expect users to make use of? Not really sure what it's for. The actual fs2/Monix integration code is all in other modules: `mu-rpc-fs2-internal` and `mu-rpc-monix-internal`.
* Those modules have a dependency on the `mu-rpc-health-check-unary` module, just for the sake of reusing 4 lines of code. I would rather copy the code and remove the dependency.
*  The `ChannelFor` class is in the `mu-common` module. I would expect to see that class in the `mu-rpc-channel` module.
* We have a lot of inter-module `test->test` dependencies, with test classes in one module extending a "base" class in another module or importing test data from another module. This is extremely hard to navigate, and the excessive re-use of test models makes it difficult to touch them without breaking a lot of code. Again, I'd be happy to copy-paste the code to the module where it's needed, and sever the inter-module dependency.
* There are a few cases where multiple modules contribute classes to the same Scala package. So just looking at a class's package does not tell you where the source file is.

**Comment by juanpedromoreno** [comment]
Thanks, @cb372.

I agree with this. The reorganization is needed to keep the project codebase as simple as possible. The only requirement I see here before reducing the number of modules is that we need to preserve the number of transitive dependencies that mu-scala would be injecting in projects using it. As a dummy example, if my project is using Monix for streaming, I wouldn't like to have fs2 dependencies because of the mu-scala dependency. The same applies to `netty` or `okhttp`.

**Comment by cb372** [comment]
Agreed 👍

**Comment by cb372** [comment]
Here is a summary of the current module structure. Arrows are compile-time dependencies. For simplicity, test dependencies are not shown. (Click to enlarge.)

![modules-current](https://user-images.githubusercontent.com/106760/80225023-6d6c5080-8642-11ea-85c9-63920161836b.png)

Here is my proposal for re-organisation:

![modules-proposal](https://user-images.githubusercontent.com/106760/80226707-9db4ee80-8644-11ea-9c85-16d49051b615.png)

Summary of changes:

* Combine the `mu-common`, `mu-rpc-internal-core` and `mu-rpc-channel` modules into a single module called `mu-rpc-service`. These modules are tightly coupled, either through dependency relationships or via references in macro-generated code, so we may as well combine them into one.
    * This module will be the only dependency you need in order to compile a `@service`-annotated service definition trait (with only unary endpoints). Right now you need to depend on `mu-rpc-channel` to compile a service definition, which I think is pretty confusing.

* Combine the `mu-health-check-unary`, `mu-rpc-fs2` and `mu-rpc-monix` modules into a single module called `mu-health-check`. This will contain both FS2 and Monix implementations, but it will declare dependencies with `optional` scope, so users only need to add a dependency on the streaming library they need. The grey arrows in the diagram indicate `optional` scope.

* Rename `mu-rpc-internal-{fs2,monix}` to `mu-rpc-{fs2,monix}`. This will not affect users, as we already tell them to depend on `mu-rpc-{fs2,monix}`, not `mu-rpc-internal-{fs2,monix}`.

* Rename `mu-rpc-{netty,netty-ssl,okhttp}` to `mu-rpc-client-{netty,netty-ssl,okhttp}` to make it clearer that they are client modules. This is purely a cosmetic change, and may be unnecessarily disruptive (e.g. scala-steward won't know that the module name has changed), so I'm open to discussion about this one.

* Move all tests to a single `tests` module (see #877). This will depend on pretty much every other module (dependency arrows are omitted from the diagram).

* Remove unnecessary dependencies (e.g. `mu-rpc-http` does not need to depend on `mu-rpc-server`)

**Comment by juanpedromoreno** [comment]
Looks good to me. Very much cleaner and clearer 💯
