### ISSUE TITLE
Major refactoring of the tests

### ISSUE THREAD

**Issue by cb372** [higherkindness/mu-scala#877]
There are `Utils`, `CommonUtils` and `FooBaseSuite`s all over the place, and a lot of inheritance going on. The tests are structured that way to enable sharing of both test data and helper functions, which is a noble goal, but it's extremely difficult to navigate.

Having the tests spread across all the different modules makes things even more complicated, especially as some tests appear to be in the wrong module, and for other tests it's not clear in which module they should live.

How about we make a new `tests` module and move all the tests to there? All the tests would live in one place, and there would be no need for complex inter-module dependencies. We could refactor the tests to reduce inheritance and re-organise the shared test data and helper functions at the same time.

**Comment by juanpedromoreno** [comment]
Makes sense to me 👍 . Actually, the new `tests` module proposal would also cover https://github.com/higherkindness/mu-scala/issues/580
